# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.AddField(
            model_name='student',
            name='interest1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='interest2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='interest3',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
