# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-27 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170906_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='professor',
            name='firstname',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='professor',
            name='lastname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
