# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-20 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20171027_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='commentCategory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
